# This is a configuration file for developing with Cloudflare Pages.
# It's intentionally kept simple to avoid conflicts with production settings.
# The production configuration is stored in 'wrangler.production.toml'.

name = "gametime-dev"
compatibility_date = "2024-06-20"

# This tells Wrangler where to find the Functions, like our proxy.
[functions]
directory = "./functions" 