# This is a configuration file for developing with Cloudflare Pages.
# It's intentionally kept simple to avoid conflicts with production settings.
# The production configuration is stored in 'wrangler.production.toml'.

# Cloudflare Pages configuration for development
name = "gametime-dev"
compatibility_date = "2024-06-20"

# Pages build configuration
pages_build_output_dir = "dist"

# Cloudflare Functions configuration
# Note: Functions directory is automatically detected
# The functions directory is expected to be at the project root 